[package]
name = "yellowstone-vixen-example-jetstreamer"
description = "Example of using Jetstream source with Yellowstone Vixen"
publish = false
edition.workspace = true
license = "MIT"
repository = "https://github.com/rpcpool/yellowstone-vixen"

[dependencies]
anyhow = "1.0"
bs58 = { workspace = true }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
yellowstone-vixen = { workspace = true }
yellowstone-vixen-core = { workspace = true }
yellowstone-vixen-jetstream-source = { workspace = true }
yellowstone-vixen-spl-token-parser = { workspace = true }
