[package]
name = "yellowstone-vixen-yellowstone-grpc-source"
version.workspace = true
edition.workspace = true
description = "Yellowstone gRPC source for the Yellowstone Vixen"
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "./README.md"

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "signal"] }
tokio-util = { workspace = true }
# align version with yellowstone-grpc-client -> cargo tree -i tonic-health
tonic-health = "0.14"
tracing = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true, features = ["sink"] }
solana-commitment-config = { workspace = true }
url = { workspace = true }
yellowstone-vixen = { workspace = true }
yellowstone-vixen-core = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
yellowstone-grpc-client = { workspace = true }
serde = { workspace = true, features = ["derive"] }
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
