[package]
name = "jetstream-replay"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
async-trait = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = "0.3"
anyhow = { workspace = true }
yellowstone-vixen = { workspace = true, features = ["prometheus"] }
yellowstone-vixen-core = { workspace = true }
yellowstone-grpc-proto = { workspace = true }
yellowstone-vixen-jetstream-source = { workspace = true, features = ["prometheus"] }
yellowstone-vixen-parser = { workspace = true, features = ["token-program"] }
prometheus = { workspace = true }
warp = { workspace = true }
