[package]
name = "yellowstone-vixen-example-filtered-pipeline"
description = "Eample of filtered pipeline"
publish = false
edition.workspace = true
license = "MIT"
repository = "https://github.com/rpcpool/yellowstone-vixen"

[dependencies]
clap = { workspace = true, features = ["derive", "cargo", "wrap_help"] }
toml = { workspace = true }
tracing = { workspace = true }
rustls = { workspace = true }
yellowstone-vixen = { workspace = true }
yellowstone-vixen-spl-token-parser = { workspace = true }

yellowstone-vixen-yellowstone-grpc-source = { workspace = true }
yellowstone-vixen-solana-rpc-source = { workspace = true }
