[package]
name = "yellowstone-vixen-example-filtered-pipeline"
description = "Eample of filtered pipeline"
publish = false
edition.workspace = true
license = "MIT"
repository = "https://github.com/rpcpool/yellowstone-vixen"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "cargo", "wrap_help"] }
toml = "0.8.12"
tracing = "0.1.40"
yellowstone-vixen = { workspace = true }
yellowstone-vixen-raydium-amm-v4-parser = { workspace = true, features = [
  "shared-data",
] }
yellowstone-vixen-meteora-amm-parser = { workspace = true }

yellowstone-vixen-yellowstone-grpc-source = { workspace = true }
yellowstone-vixen-solana-rpc-source = { workspace = true }
