[package]
name = "yellowstone-vixen-example-fumarole"
description = "Example of configuring fumarole source"
publish = false
edition.workspace = true
license = "MIT"
repository = "https://github.com/rpcpool/yellowstone-vixen"

[dependencies]
clap = { version = "4.5.4", features = ["derive", "cargo", "wrap_help"] }
toml = "0.8.12"
tracing = "0.1.40"
yellowstone-vixen = { workspace = true, features = ["prometheus"] }
prometheus = { version = "0.14.0", features = ["push"] }
tokio = { version = "1.39.3", features = ["rt", "rt-multi-thread"] }
yellowstone-vixen-parser = { workspace = true }
borsh = { workspace = true, features = ["derive"] }
yellowstone-vixen-yellowstone-fumarole-source = { workspace = true }
yellowstone-vixen-spl-token-parser = { workspace = true }
yellowstone-vixen-spl-token-extensions-parser = { workspace = true }
rustls = { workspace = true }
prost = { workspace = true, features = ["derive"] }
